name: Composite Action Demo
on: [push]
jobs:
  run-composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./  # Asume que tu composite action está en la raíz del repo
        with:
          who-to-greet: "GitHub"